Servicecloud/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>No_of_Months__c</fullName>
        <label>No of Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>No_of_Years__c</fullName>
        <label>No. of Years</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percent_per_month__c</fullName>
        <label>percent per month</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Percent_per_year__c</fullName>
        <label>Percent per Year</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Servicecloud/src/classes/SalesRepComission.cls
public class SalesRepComission {
    public List<user> lstusers{get;set;}
    public SalesRepComission(){
        list<string> lststrprofilesa = system.label.lststrprofiles.split(';');
        list<profile> lstprofile = [select id from profile where name IN : lststrprofilesa];
        lstusers = [select id,name,Percent_per_month__c,Percent_per_year__c,No_of_Years__c,No_of_Months__c from User where profileId IN : lstprofile];  
    }
    public pagereference ListUsers() {
        system.debug(lstusers+'this is the list of users');   
        try{
        update lstusers;  
            apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.Confirm,'Update Success!');
            apexpages.addmessage(msg);
        }
        catch(exception e){
           apexpages.Message msg = new Apexpages.Message(ApexPages.Severity.Error,'Opps!: '+e.getMessage()); 
           apexpages.addmessage(msg);
        }
        
        return null;
    } 
}